// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	core "github.com/gardener/gardener/pkg/apis/core"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNamespacedCloudProfiles implements NamespacedCloudProfileInterface
type FakeNamespacedCloudProfiles struct {
	Fake *FakeCore
	ns   string
}

var namespacedcloudprofilesResource = core.SchemeGroupVersion.WithResource("namespacedcloudprofiles")

var namespacedcloudprofilesKind = core.SchemeGroupVersion.WithKind("NamespacedCloudProfile")

// Get takes name of the namespacedCloudProfile, and returns the corresponding namespacedCloudProfile object, and an error if there is any.
func (c *FakeNamespacedCloudProfiles) Get(ctx context.Context, name string, options v1.GetOptions) (result *core.NamespacedCloudProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(namespacedcloudprofilesResource, c.ns, name), &core.NamespacedCloudProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*core.NamespacedCloudProfile), err
}

// List takes label and field selectors, and returns the list of NamespacedCloudProfiles that match those selectors.
func (c *FakeNamespacedCloudProfiles) List(ctx context.Context, opts v1.ListOptions) (result *core.NamespacedCloudProfileList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(namespacedcloudprofilesResource, namespacedcloudprofilesKind, c.ns, opts), &core.NamespacedCloudProfileList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &core.NamespacedCloudProfileList{ListMeta: obj.(*core.NamespacedCloudProfileList).ListMeta}
	for _, item := range obj.(*core.NamespacedCloudProfileList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested namespacedCloudProfiles.
func (c *FakeNamespacedCloudProfiles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(namespacedcloudprofilesResource, c.ns, opts))

}

// Create takes the representation of a namespacedCloudProfile and creates it.  Returns the server's representation of the namespacedCloudProfile, and an error, if there is any.
func (c *FakeNamespacedCloudProfiles) Create(ctx context.Context, namespacedCloudProfile *core.NamespacedCloudProfile, opts v1.CreateOptions) (result *core.NamespacedCloudProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(namespacedcloudprofilesResource, c.ns, namespacedCloudProfile), &core.NamespacedCloudProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*core.NamespacedCloudProfile), err
}

// Update takes the representation of a namespacedCloudProfile and updates it. Returns the server's representation of the namespacedCloudProfile, and an error, if there is any.
func (c *FakeNamespacedCloudProfiles) Update(ctx context.Context, namespacedCloudProfile *core.NamespacedCloudProfile, opts v1.UpdateOptions) (result *core.NamespacedCloudProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(namespacedcloudprofilesResource, c.ns, namespacedCloudProfile), &core.NamespacedCloudProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*core.NamespacedCloudProfile), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNamespacedCloudProfiles) UpdateStatus(ctx context.Context, namespacedCloudProfile *core.NamespacedCloudProfile, opts v1.UpdateOptions) (*core.NamespacedCloudProfile, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(namespacedcloudprofilesResource, "status", c.ns, namespacedCloudProfile), &core.NamespacedCloudProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*core.NamespacedCloudProfile), err
}

// Delete takes name of the namespacedCloudProfile and deletes it. Returns an error if one occurs.
func (c *FakeNamespacedCloudProfiles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(namespacedcloudprofilesResource, c.ns, name, opts), &core.NamespacedCloudProfile{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNamespacedCloudProfiles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(namespacedcloudprofilesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &core.NamespacedCloudProfileList{})
	return err
}

// Patch applies the patch and returns the patched namespacedCloudProfile.
func (c *FakeNamespacedCloudProfiles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *core.NamespacedCloudProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(namespacedcloudprofilesResource, c.ns, name, pt, data, subresources...), &core.NamespacedCloudProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*core.NamespacedCloudProfile), err
}
